### ISSUE TITLE
Validate kappa maps generated by mockgen for 1LPT

### ISSUE THREAD

**Issue by marcelo-alvarez** [exgalsky/mockgen#2]
Verify that changes after merging https://github.com/exgalsky/lpt/pull/8, https://github.com/exgalsky/mockgen/pull/1, https://github.com/exgalsky/xgfield/pull/7 result in the expected statistical properties of full sky kappa maps for the input cosmology, assuming 1LPT is used for the matter fluctuations.

**Comment by marcelo-alvarez** [comment]
@abaleato the first kappa maps are obviously wrong, it looks like there is only the particle shot noise present in the maps (i.e. Cl \propto 1/N^3 where N is the cube root of the number of particles in the simulation, as labeled in the plot below; don't mind the noise at high-ell, these maps were only binned to Nside=1024, unlike the map used for websky-6144 which was binned at Nside=4096).

I suspect there is some normalization factor off in the transfer function that makes the displacements negligible so there is no clustering in the matter. I will investigate further and may involve getting started on https://github.com/exgalsky/lpt/issues/5.

![Image](https://github.com/exgalsky/mockgen/assets/32470484/02a730ca-2d4d-4e10-93da-73d42b5457fd)

**Comment by abaleato** [comment]
I see. No worries. Just let me know when you've got something I can validate.

**Comment by marcelo-alvarez** [comment]
@abaleato the first batch of (10) kappa maps for you to validate are being written to:
```
/global/cfs/cdirs/mp107d/exgal/users/malvarez/tests/mockgen/output/kappa_mockgen-2_135[79-88]-2048_nside-4096.fits
```
These were generated by the command
```
srun -n 16 mockgen mockgen-2 --N 2048 --Niter 10 --Nside 4096
```
with the [xgsmenv environment ](ttps://github.com/exgalsky/xgsmenv) on 4 Perlmutter GPU nodes.

The cosmological parameters passed to CAMB were:
```
            'T_cmb': 2.72548,
            'h': 0.68,
#=================Omegas========================
            'Omega_m': 0.31,      # Matter density fraction
            'Omega_b': 0.0493890, # baryon density fraction
            'Omega_k': 0.,
#=============Spectral params===================
            'A_s': 2.10058e-9,   # scalar amplitude
            'n_s': 0.96605,      # scalar spectral index
            'alpha_s': 0.,       # scalar spectral running
            'k_pivot': 0.05,     # pivot scale for scalar perturbations
            'r': 0.,             # tensor to scalar ratio
            'n_t': 0.,           # tensor spectral index
            'alpha_t': 0.,       # tensor spectral running
            
#=============reionization========================
            'tau_reion': 0.0543,    # optical depth at reionization
            'YHe': 0.2454,          # Helium fraction
#=============Light relics===========================
            'N_ur': 2.0328,     # Ultra-relativistic species (ultra-light neutrinos)
            'N_ncdm': 1,        # Light massive relics including massive neutrinos
            'm_ncdm': 0.06,     # mass of non-cold light relics
#===========DE EOS===================================
            'w0': -1.,         
            'wa': 0.
```

Box size = 7700 Mpc at 2048^3 resolution. The redshift range integrated over was 0.05 < z < 4.5. Note that the lensing kernel used is for a comoving distance to the last scattering surface of 13.8 Gpc.

This is a moderate-to-low resolution run, with 10 independent realizations (one kappa map per) so as not to waste Perlmutter GPU cycles. If necessary at this stage higher resolutions can be done. Please let me know if you have any questions. Thanks!

**Comment by abaleato** [comment]
Got it. Thanks! I'll let you know when I have something to show.

**Comment by abaleato** [comment]
@marcelo-alvarez I don't seem to have permission to read `/global/cfs/cdirs/mp107d/exgal/users/malvarez/tests/mockgen/output/`

**Comment by marcelo-alvarez** [comment]
> @marcelo-alvarez I don't seem to have permission to read `/global/cfs/cdirs/mp107d/exgal/users/malvarez/tests/mockgen/output/`

@abaleato should be fixed now.

**Comment by abaleato** [comment]
@marcelo-alvarez Did you check these against Websky? I just did a preliminary check against theory and see some significant divergences. Though of course I may have put some bugs in somewhere!
![Screenshot 2024-02-05 at 3 03 06 PM](https://github.com/exgalsky/mockgen/assets/48951377/4956b091-79a1-4a26-b907-4807c9c73f42)

**Comment by marcelo-alvarez** [comment]
@abaleato I did a quick check, yes. Is this integrating from z=0.05 to z=4.5 (which is the interval used in the maps)?

**Comment by abaleato** [comment]
Yep, 0.05<z<4.5. I'll dig deeper to make sure I haven't messed up somewhere.

P.S. Here's an updated plot where I've fixed the low-ell issues in 1LPT (I wasn't going low enough in k).

![Screenshot 2024-02-05 at 4 22 28 PM](https://github.com/exgalsky/mockgen/assets/48951377/48aa0681-242a-4cf3-8f0c-52fa9f7cfe99)

**Comment by marcelo-alvarez** [comment]
That's a bummer. Would it help to compare the z=0 matter power spectrum used? I wrote it to the file
```
$CFS/mp107d/exgal/users/malvarez/tests/mockgen/matterpower.npz
```
 by adding
```
        if self.mpiproc == 0:
            np.savez('matterpower.npz',k_Mpc=k,pk_Mpc3=pk)
```
after [line 41 of mockgen/sky.py](https://github.com/exgalsky/mockgen/blob/main/mockgen/sky.py#L41). Units are in $1/{\rm Mpc}$ and ${\rm Mpc}^3$ i.e. without factors of $h$.

The plot below was generated with
```
python $CFS/mp107d/exgal/users/malvarez/tests/mockgen/showmatterpower.py
```

![matterpower](https://github.com/exgalsky/mockgen/assets/32470484/86007ea7-2471-48bb-ac99-8f9dac7187c2)

**Comment by abaleato** [comment]
Your Plin(z=0) is actually 5% higher than mine across all ks, but I think that difference would pull us _away_ from reconciliation...

**Comment by abaleato** [comment]
Again, let me double check things on my end, because it's quite likely I have a bug

**Comment by marcelo-alvarez** [comment]
> Your Plin(z=0) is actually 5% higher than mine across all ks, but I think that difference would pull us _away_ from reconciliation...

At least that indicates there is some kind of mismatch in cosmology. So it's still possible that the difference in evolution towards higher z would go in the right direction. 

I will see about having CAMB output the exact parameters used (what I copied above was actually based on the default values in [our own interface to CAMB](https://github.com/exgalsky/xgcosmo/blob/main/xgcosmo/cosmology.py#L42-L81) as well as those that we [modified](https://github.com/exgalsky/mockgen/blob/main/mockgen/sky.py#L98) with our [own defaults](https://github.com/exgalsky/mockgen/blob/main/mockgen/defaults.py#L11-L12) (omegam=0.31 and h=0.68).

**Comment by marcelo-alvarez** [comment]
> Again, let me double check things on my end, because it's quite likely I have a bug

Sure, no problem, thanks for double checking! 

I will hold off on having CAMB output the exact parameters then, until I hear back...

**Comment by abaleato** [comment]
Ta-daaa. It was a bug of mine, of course. Looks great! :)

(Note that the CAMB result is fully non-linear and goes up to z=1100, where the 1LPT curve covers 0.05<z<4.5.)

![Screenshot 2024-02-05 at 5 48 27 PM](https://github.com/exgalsky/mockgen/assets/48951377/daca001c-bdc7-4ee7-80e8-267d1987115e)

**Comment by marcelo-alvarez** [comment]
Excellent. There are many more tests we could do, but I think they would also be applicable to 2lpt, fully nonlinear, etc, so let's consider this done and move on. Thanks!
